locale: en-US
title: Gradients
title_separator: '-'
name: Ritwik Gupta
description: Innovating at the intersection of machine learning and health.
url: 'https://ritwikgupta.me'
baseurl: ''
repository: RitwikGupta/ritwikgupta.github.io
teaser: null
breadcrumbs: false
words_per_minute: 115
read_more: enabled
comments:
  provider: null
  disqus:
    shortname: null
  discourse:
    server: null
  facebook:
    appid: null
    num_posts: null
    colorscheme: null
staticman:
  allowedFields:
    - name
    - email
    - url
    - message
  branch: gh-pages
  commitMessage: New comment.
  filename: 'comment-{@timestamp}'
  format: yml
  moderation: true
  path: '_data/comments/{options.slug}'
  requiredFields:
    - name
    - email
    - message
  transforms:
    email: md5
  generatedFields:
    date:
      type: date
      options:
        format: iso8601
atom_feed:
  path: null
google_site_verification: null
bing_site_verification: null
alexa_site_verification: null
yandex_site_verification: null
twitter:
  username: null
facebook:
  username: null
  app_id: null
  publisher: null
og_image: null
social:
  type: null
  name: null
  links: null
analytics:
  provider: google-universal
  google:
    tracking_id: UA-60715523-1
author:
  name: Ritwik Gupta
  avatar: profile.jpg
  bio: >-
    Focusing on the intersection of machine learning + humanitarian assistance and disaster response. Frequent forays
    into systems engineering and robotics. Generalist.
  location: 'San Francisco, CA'
  employer: Neural Tangent
  googlescholar: null
  email: null
  uri: null
  bitbucket: null
  codepen: null
  dribbble: null
  flickr: null
  facebook: null
  foursquare: null
  github: "RitwikGupta"
  google_plus: null
  keybase: null
  instagram: null
  lastfm: null
  linkedin: "ritwikgupta"
  orcid: "https://orcid.org/0000-0001-7608-3832"
  pinterest: null
  soundcloud: null
  stackoverflow: null
  steam: null
  tumblr: null
  twitter: "Ritwik_G"
  vine: null
  weibo: null
  xing: null
  youtube: null
  wikipedia: null

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - '*.sublime-project'
  - '*.sublime-workspace'
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: utf-8
markdown_ext: 'markdown,mkdown,mkdn,mkd,md'
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: |+


incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: 'lsquo,rsquo,ldquo,rdquo'
  enable_coderay: false
collections:
  teaching:
    output: true
    permalink: '/:collection/:path/'
  publications:
    output: true
    permalink: '/:collection/:path/'
  portfolio:
    output: true
    permalink: '/:collection/:path/'
  talks:
    output: true
    permalink: '/:collection/:path/'
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ''
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ''
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ''
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ''
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  - scope:
      path: ''
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true
sass:
  sass_dir: _sass
  style: compressed
permalink: '/:categories/:title/'
timezone: America/Los_Angeles
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
compress_html:
  clippings: all
  ignore:
    envs: development
